### ISSUE TITLE
Improve return status code when key not found in cache

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#122]
On line https://github.com/massalabs/station-massa-wallet/blob/7a2437c2f11b12d96e1475a4dc393c75e764643c/internal/handler/wallet/sign.go#L107 we return an error 500, but it should be 404 if the error is a not found error from the cache.

_Originally posted by @Thykof in https://github.com/massalabs/thyra-plugin-wallet/pull/121#discussion_r1182362626_
            

User story: as a developer when I use Massa Station API, I want to receive http status code 404 when the correlation id I provide in the request is not found in cache.

**Comment by SlnPons** [comment]
@Thykof to make sure I understand the user flow here. Could you confirm that the follow user story is summarising what you're talking about? 

As a user, when I try to import an account by adding a private key and that this private key doesn't exist, I receive a non-straightforward error message (from the BE and so in the FE).

**Comment by Thykof** [comment]
No, it's okay from a user point of view. This issue is about improving the accuracy of HTTP status code.

**Comment by SlnPons** [comment]
Ah ok, thanks @Thykof for clarifying. Who's working on it currently?

**Comment by Thykof** [comment]
nobody is working on it, I just pushed a PR yesterday during investigation/clarification of the issue. Waiting for prioritization to really fix it and test the fix.

**Comment by pivilartisant** [comment]
After time boxing, I was blocked due to a problem with implementing a mock cache using gcache. I have commented the test out so it can we reworked.

**Comment by longgamma-massa** [comment]
@Thykof we should sync on this

**Comment by Thykof** [comment]
what needs to be done is writing unit test and make sure it's working properly. The PR is a bit old now, so we might have to redo it (no big deal)
