### ISSUE TITLE
Web: use typescript for mirage

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#338]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

https://github.com/massalabs/thyra-plugin-wallet/pull/336/files

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by maxime-carabina** [comment]
Solved by : #470
