### ISSUE TITLE
Sign tx wails pop-up: can't see the decimal

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#420]
**Describe the bug**
When I send an amount with decimal, I can't see it in the wails pop-up when signing the tx. 

<img width="906" alt="image" src="https://github.com/massalabs/thyra-plugin-wallet/assets/109611779/81c6ef10-8d9d-42da-8c08-e9f3498e7e85">

**To Reproduce**
Try to send a tx with decimals and click on "confirm and sign" on the confirmation screen of the wallet. 
You cannot see the decimals (see screenshot)

**You should see the exact amount that you are sending.**

 - Version: 0.1.1 of the MassaWallet

**Comment by maxime-carabina** [comment]
@SlnPons Mario took care of it.
Here's a screen: 
![image](https://github.com/massalabs/station-massa-wallet/assets/72019005/151d3bf1-6966-47e2-9047-d56999a23cf7)

Can you re-check on your side for me ? 🤔

**Comment by SlnPons** [comment]
@maxime-carabina you're right. It's solved. 
Closing this issue :)
