### ISSUE TITLE
MacOS only: change the logo of the app in the dock

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#423]
**Context**
Prevent / remove "wallet-plugin" terminal from opening on user's desktop as it is super confusing and not user friendly
<img width="297" alt="image" src="https://github.com/massalabs/thyra-plugin-wallet/assets/109611779/1e7ae502-9fa3-4842-9f20-6a690eed06f1">

**User flow**
1. Install MassaStation
2. Open MassaStation home page
3. Install the wallet (or if you have it already)
4. Open it
5. See the wallet-plugin terminal (see screenshot)

<img width="458" alt="image" src="https://github.com/massalabs/thyra-plugin-wallet/assets/109611779/0bc9283a-bdfa-4dfe-9f3b-ac625f494e5c">

**How to**

- [ ] Test on other OS if this happens too (I tested on MacOS, so need to be tested on Windows and Linux ubuntu)
- [ ] Try to see if it's wails: https://wails.io/fr/docs/reference/options
- [ ] Find the problem if not wails and try to correct it

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
The problem does not appear on ubuntu

**Comment by mazmassa** [comment]
> The problem does not appear on ubuntu

Indeed, it's only on MacOs.

**Comment by Thykof** [comment]
QA instructions:
- install Massa Station
- remove the plugin wallet if installed
- quit Massa Station
- on a terminal on wallet repo and run `task generate && task build && task install-plugin`
- open Massa Station
- see the beautiful icon!

**Comment by Thykof** [comment]
@longgamma-massa question about the product: it's "Massa Wallet" in the store. I think it should be same in the dock:

![Image](https://github.com/massalabs/station-massa-wallet/assets/11590067/ec7721e3-1f5e-4863-abf3-f0e3e46d4971)

**Comment by longgamma-massa** [comment]
Agreed, use the official name
