### ISSUE TITLE
No way to go back to the wallet-plugin

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station-massa-wallet#428]
When i click on add account ![image](https://github.com/massalabs/station/assets/16623956/2b2e6fc8-b0d7-4fce-b8ab-79ce9eb4c862), I have no way to come back to the previous page, except using the back function of the browser

**Comment by maxime-carabina** [comment]
The feature is not present in the design actually, but it could improve the user experience.

@SlnPons What do you think of that?

I suggest we deal with this point after the next release.

**Comment by SlnPons** [comment]
@LucasF243 fyi, probably sth that we would like to improve in the next version ;) 
Please ack

**Comment by LucasF243** [comment]
Yes indeed, we could find a solution, even if we don't necessarily need to add a back button like the browser already has. I think it's more important to have the possibility of having the flow for adding an account that doesn't leave the page, perhaps in a pop-up window

**Comment by LucasF243** [comment]
flow to add an account: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=5637%3A26773&mode=design&t=BZu9NVlpvwvnhxr2-1

**Comment by longgamma-massa** [comment]
@mazmassa need your validation for this UX improvement.

**Comment by mazmassa** [comment]
... something like that is acceptable!? 

<img width="1252" alt="Screenshot 2023-08-22 at 18 38 10" src="https://github.com/massalabs/station-massa-wallet/assets/126461030/c1089d1e-c221-4b20-985c-fcbeecd551ef">

**Comment by pivilartisant** [comment]
> ... something like that is acceptable!?
> <img alt="Screenshot 2023-08-22 at 18 38 10" width="1252" src="https://user-images.githubusercontent.com/126461030/262423726-c1089d1e-c221-4b20-985c-fcbeecd551ef.png">

This would be a more efficient solution, knowing that if we go for the modal, there will surely be code duplication

**Comment by pivilartisant** [comment]
> ![9630982966d25037887c20b3262421af](https://user-images.githubusercontent.com/126561114/262672138-3061a8ef-9efe-4d01-8577-cd9b0f56771f.png)
> 
> if we have to use this solution, just a cross to close the creation flow is enough

@mazmassa  wdyt ?

**Comment by pivilartisant** [comment]
> > ![9630982966d25037887c20b3262421af](https://user-images.githubusercontent.com/126561114/262672138-3061a8ef-9efe-4d01-8577-cd9b0f56771f.png)
> > if we have to use this solution, just a cross to close the creation flow is enough
> 
> @mazmassa wdyt ?
@longgamma-massa  do you think it is sufficient for user in terms of UX ?

**Comment by mazmassa** [comment]
> if we have to use this solution, just a cross to close the creation flow is enough

I don't want to be picky but a page with a cross to close... personally I found weird.
Remember this is a page, not a modal or related.

If we displayed the page like: https://mdbootstrap.com/docs/standard/extended/full-screen-modal/
I would understand a close button. 
But we are not doing that. Users land as a regular page, so, I would go for a link (up, down, side) etc mentioning. But it's up to you to decide.

**Comment by LucasF243** [comment]
As I said above, there are 2 solutions:
1) We use a modal and then we can add navigation elements (ex: add a wallet on metamask)
2) We use a full page without modal effect, and the navigation elements are those of the browser (ex: add an account on disney +).
There are no bad solutions, but imo we should leave it like that

**Comment by longgamma-massa** [comment]
@mazmassa @LucasF243 Instead of so many back-and-forths, why not a quick call and agree on the best approach? :)

**Comment by mazmassa** [comment]
It should be fine now!

We addressed it here: https://github.com/massalabs/station-massa-wallet/pull/666 and it should be available in the next release.

Let you close the issue @longgamma-massa if is all good on your side! 🙏
