### ISSUE TITLE
path /testPlugin/transfer-coins was not found

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station-massa-wallet#430]
I have an error:
```
{"code":404,"message":"path /testPlugin/transfer-coins was not found"}
```
even if in another tab, it works...

![image](https://github.com/massalabs/thyra-plugin-wallet/assets/16623956/e2f1ac17-1daf-4706-9f12-4e46ba10e106)

**Comment by gregLibert** [comment]
here: 
```
https://station.massa/plugin/massalabs/wallet/web-app/send-redirect/?to=AU12DDPzndXjaVXvGuFHBfLh3YqufrbTZWVPztXWD3QmK3FNe9THT&amount=100
```

**Comment by maxime-carabina** [comment]
@gregLibert Could you give me a bit more context?

Because I can't reproduce this bug.

**Comment by Thykof** [comment]
The correct URL is: https://station.massa/plugin/massa-labs/massa-wallet/web-app/send-redirect/ 

see `massa-labs/massa-wallet` because we renamed the wallet plugin author and name. It's possible that somewhere in the code we use the old ones.

**Comment by maxime-carabina** [comment]
> I think that this issue was fixed with #416

@Pierregvx No! This problem may be caused by the router. 🤔 
It does not come from the backend but undoubtedly from the frontend.

**Comment by Pierregvx** [comment]
this fix is from the frontend : 
before if you clicked on a redirect url I would redirect you to the /web/transfer-coin?to=anaddress&amount=anamount
and then change the state of the url to remove the params
but it didn'have routefor in the replaceState so it changed the url to `/transfer-coin` instead of `/web/transfer-coin`

**Comment by maxime-carabina** [comment]
Routes in the frontend are not wrapped to depend on the user selected.

At the moment, they are like this:
```typescript
<Route path=":nickname/home" element={<Home />} />
<Route path=":nickname/transactions" element={<Transactions />} />
<Route path=":nickname/transfer-coins" element={<TransferCoins />} />
``` 

But they should be like this:
```typescript
<Route path=":nickname" element={<Wrapper />}>
    <Route path="home" element={<Home />} />
    <Route path="transactions" element={<Transactions />} />
    <Route path="transfer-coins" element={<TransferCoins />} />
</Route>
```

**Comment by maxime-carabina** [comment]
> this fix is from the frontend : before if you clicked on a redirect url I would redirect you to the /web/transfer-coin?to=anaddress&amount=anamount and then change the state of the url to remove the params but it didn'have routefor in the replaceState so it changed the url to `/transfer-coin` instead of `/web/transfer-coin`

That's right! If the routes were as I've just written in the previous message, we could remove the `window.history.replaceState`

**Comment by Pierregvx** [comment]
> > this fix is from the frontend : before if you clicked on a redirect url I would redirect you to the /web/transfer-coin?to=anaddress&amount=anamount and then change the state of the url to remove the params but it didn'have routefor in the replaceState so it changed the url to `/transfer-coin` instead of `/web/transfer-coin`
> 
> 
> 
> That's right! If the routes were as I've just written in the previous message, we could remove the `window.history.replaceState`

I see ! I think we still need it to remove the params but we can remove the routefor

**Comment by maxime-carabina** [comment]
> 

Why do you want to remove the params? 🤔

**Comment by Pierregvx** [comment]
solved in https://github.com/massalabs/station-massa-wallet/pull/416
we will refactor the routes in https://github.com/massalabs/station-massa-wallet/issues/472
