### ISSUE TITLE
Update Wallet manifest

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#443]
Update manifest with correct name and description + add the logo to the repo

Expected: 
{
    "author" : "Massa Labs",
    "name" : "Massa Wallet",
    "description" : "Massa blockchain official wallet",
}

**Comment by pivilartisant** [comment]
@SlnPons

**Comment by SlnPons** [comment]
Additional questions: 
- What's the current logo?
- And finally what are the existing tests about the manisfest on this repo?
- (It seems that we have diff tests on diff repo regarding the manifest....)

**Comment by pivilartisant** [comment]
logo seems to be missing from the repo

**Comment by SlnPons** [comment]
> logo seems to be missing from the repo

--> that's maybe why we have a problem to get the logo. Isn't it @Pierregvx ?!

Could you use this one please? 
![Shape-58 svg](https://github.com/massalabs/station-massa-wallet/assets/109611779/b20d7721-1f68-46f1-b99e-27fa2730ad7a)
