### ISSUE TITLE
Sign tx pop-up - improve keyboard usage: enter key usage

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#449]
**Context**

Prevent user to show password to everyone if pressing "enter" on the keyboard. 
At the moment, when a user is on the wails sign tx pop-up and click on "enter" using keyboard, it activate the "show password" action. We should prevent that.

**User flow**
As a user, when I am signing a transaction using the wails pop-up, I want to be able to click on the "enter" key of my keyboard and have the action "Sign" selected and pressed. 

Another acceptable option is: 
As a user, when I am signing a transaction using the wails pop-up, I want to click on the "enter" key of my keyboard and that nothing happens.

**Technical details**
edit @pivilartisant 
it seems like we need to add a special function to handle key events, something  like :

```tsx
export function handleKeyDown(e: React.KeyboardEvent<HTMLFormElement>) {
  if (e.key === 'enter') {
    e.preventDefault();
    //add logic here
  }
}
```

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by pivilartisant** [comment]
Yess essential for security

**Comment by mazmassa** [comment]
> it seems like we need to add a special function to handle key events, something like :
> export function handleKeyDown(e

I guess you don't need that. 

The field is being fired because theres a button under the hood in the eye icon.
I guess it would be enough if we wrap the wails fields and the cancel/ok buttons in a `<form>` tag and use type submit. When enter is pressed is that form that will submit and not the button under the file that will fired.

Should be easily fixed! :)

**Comment by SlnPons** [comment]
This doesn't work on my side on the main branch of the wallet.

**Comment by pivilartisant** [comment]
https://github.com/massalabs/station-massa-wallet/pull/487 BTW  I have re-opened this PR which fixes the enter-key problem. I does not send the form :/ will change according to our sync about the rework
