### ISSUE TITLE
Improve back-up fonction - show key pairs 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#450]
**Context**
In the back-up fonction, it's written "show key pairs" but we only show "private key". We can easily improve this. 

**User flow**

As a user, when I click on "back-up" function and then and "Show key pairs" button in the pop-up, I want to see both public and private keys displayed. 
First: public key
Second: private key 
It can be both in the same screen but display in this order please

**How to**

- [ ] Add public key info the in wails pop-up

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
I feel like we broke the UI here .... 
Here is what I see: 


![Image](https://github.com/massalabs/station-massa-wallet/assets/109611779/93139f79-8b10-48e9-904b-4fcf7f366ee7)

(large button + large field = not the same margins as on previous screens). 

But here is how the previous screens look like: 


![Image](https://github.com/massalabs/station-massa-wallet/assets/109611779/65ce526e-b9f4-4f3b-90e5-17f47e7eb5fd)



![Image](https://github.com/massalabs/station-massa-wallet/assets/109611779/e474566d-fb88-465c-b3bc-fd6c19ca57ad)


--> I expect the last screen to follow the same basics in terms of button size and margins.
This is a regression.

**Comment by pivilartisant** [comment]
> I feel like we broke the UI here .... Here is what I see:
> 
> ![Image](https://user-images.githubusercontent.com/109611779/250909621-93139f79-8b10-48e9-904b-4fcf7f366ee7.png)
> 
> (large button + large field = not the same margins as on previous screens).
> 
> But here is how the previous screens look like:
> 
> ![Image](https://user-images.githubusercontent.com/109611779/250909789-65ce526e-b9f4-4f3b-90e5-17f47e7eb5fd.png)
> 
> ![Image](https://user-images.githubusercontent.com/109611779/250909823-e474566d-fb88-465c-b3bc-fd6c19ca57ad.png)
> 
> --> I expect the last screen to follow the same basics in terms of button size and margins. This is a regression.

fixed here : https://github.com/massalabs/station-massa-wallet/pull/497

**Comment by Thykof** [comment]
I reopen because we have an open PR https://github.com/massalabs/station-massa-wallet/pull/497
