### ISSUE TITLE
Account name with underscore: poorly handle in the dropdown list

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#454]
**Describe the bug**
When I create an account with an underscore in the name; I can't see it correctly in the dropdown.

**To Reproduce**
Create an account with a "_" in the name.

**Expected behavior**
You should be able to read that there is an underscore in the name. 
--> it seems to be a pb of font colour as you can see it lightly.... 

**Screenshots**
<img width="325" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/109611779/baf66e8d-27b8-4283-80ff-ad7c8f7ccf94">

**Wallet version**
v0.1.1

**Desktop (please complete the following information):**
 - OS:MacOS

**Comment by maxime-carabina** [comment]
This problem comes from the UI-KIT.
So solved in this PR : https://github.com/massalabs/ui-kit/pull/275
