### ISSUE TITLE
Unexpected error when trying to send a tx with no fees

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#455]
**Describe the bug**
When you want to send a tx with Massa Wallet with 0 fees, you have a NaN message displayed on the send confirmation page.

**To Reproduce**

1. Go the send / receive page
2. Set up a tx to be send
3. CLick on advance
4. Select custom fees and enter 0 in the amount field
5. Click on "confirm fees"
6. Click on send 
7. See the confirmation page with NaN

**Expected behavior**
User should be able to send a tx with 0 fee 
And the confirmation screen should report correctly this amount

--> the problem may come from the "none" nMAS fees reported ... to be confirmed

**Screenshots**
<img width="377" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/109611779/b6916bf4-ecc0-4d4e-9fec-78dca4d94f8b">

**Wallet version**
v0.1.1

**Desktop (please complete the following information):**
 - OS: MacOS (but it's on all OS)

**Additional context**

**Comment by mazmassa** [comment]
> @mazmassa setting the fees to '0' instead of 'none' here and l33 solves this issue. Can we do a pr with these changes or was it set to none for a reason ?
> 
> https://github.com/massalabs/station-massa-wallet/blob/70596effaa7e82c33c82162101a329b775d8d3c6/web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx#L47-L48

Great! I guess you can... However, why we would send 0 fees!? Shouldn't we set an error when the fees is zero?

**Comment by SlnPons** [comment]
@mazmassa because it's possible to send a tx with 0 fees, I'll just take a long time if the network is saturated and if it is not well it will be easy and possible :)
So we shouldn't prevent user from doing it. But not encouraging it by default as for non-expert users it will be very hard to know if the network is full or not and so to calculate this...
