### ISSUE TITLE
Create assets page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#457]
**Context**
Create the assets page to Massa Wallet to enable users to add and manage different token types. 
This can be done if the block API enable us to get info about the different SCs

**User flow**

Designs: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=4942-29748&mode=design&t=iK1j9H8cY1JZUR3V-0
Note: as any other wallet page, this page should follow the wallet rules and standards. If for some reasons, you need to change the existing rules for this page to work better; make sure to change them on all the page to assure consistency across the all application!

**How to**
- [x] #554
- [ ] Retrieve data from the BE https://github.com/massalabs/station-massa-wallet/issues/539
- [ ] #557
- [x] UPDATED NEED: display assets on the homepage -> To be tackled in the follow up issue #566 

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow the user flow and designs

**Comment by SlnPons** [comment]
Duplicated from https://github.com/massalabs/station-massa-wallet/issues/93 
Check comment in this issue if needed for the tech strategy.

**Comment by longgamma-massa** [comment]
@LucasF243 please provide the link to finalized and approved designs once you unify them in the Wallet Final folder.

**Comment by LucasF243** [comment]
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=4942%3A29748&mode=design&t=cSdIjFv8Af1eEC0B-1

**Comment by longgamma-massa** [comment]
Q/a tests finished:
- Import Massa Bridge tokens WETH and tDAI  - done
- Error with wrong address - done
- Error with already existing Asset - done 
- Error with no input - done
- Delete token - done

**Fixes:**
- [ ]  Import token window -> only to remove the word 'hash'.
<img width="633" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/113043914/316c21ad-c3ca-4acd-8eba-5da40c07cb16">

 **Blockers:**
- While running the 'main' version I couldn't test what happens during the token balance change (tried bridging tokens but the 'main' wallet version is not recognized by the Bridge). We need to find the way to test it @pivilartisant @Thykof

**Comment by Thykof** [comment]
> Import token window -> only to remove the word 'hash'.

done in #605 

> Blockers:
> While running the 'main' version I couldn't test what happens during the token balance change (tried bridging tokens but the 'main' wallet version is not recognized by the Bridge). We need to find the way to test it @pivilartisant @Thykof

we need to sync on this @longgamma-massa
