### ISSUE TITLE
total amount not checked in transfer

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-massa-wallet#462]
**Describe the bug**
The validation functions in the transfer page are checking if the amount sent & the fees are inferior to the total balance but not the amount + fees 

**To Reproduce**
select max in the transfer page, then confirm the operation

**Expected behavior**
refuse the transaction because the user doesn't have enough for the fees + the amount

**Screenshots**

**MassaWallet version**
0.2.3

**Comment by SlnPons** [comment]
@Pierregvx please use the template to create issues. That is said, you wrote 2 opposite things here so just to make sure I understand the problem: 
Currently the validation function is NOT checking if (amount + fees) < totalBalance. It is only checking that amount < totalBalance. 
Is that correct?

**Comment by SlnPons** [comment]
Nice error message, well done @Pierregvx ;)
