### ISSUE TITLE
task build-run dependencies installation

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/station-massa-wallet#465]
Running task build-run does not seem to launch the npm install command for the web-frontend folder

1. Run task build-run on a computer that does not have the required dependencies

**Expected behavior**
Npm install should be ran

**Screenshots**
![image](https://github.com/massalabs/station-massa-wallet/assets/45430752/dfef3af9-de75-4565-b513-64d99f5242c0)

**WalletVersion**
Latest

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Thykof** [comment]
@ASAPSegfault npm install is a go:generate command, to execute it, please run `task generate`
