### ISSUE TITLE
Add Cypress

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station-massa-wallet#475]
**Context**
We don't have any setup defined for our acceptance (e2e) tests.

**User flow**
- N/A

**How to**
- N/A

**Technical details**
We must install and configure Cypress to be able to create our acceptance tests. This will allow us to do that and many other interest things in terms of tests. Much more that the current one we already have using Jest.
This must be set in all repos: Wallet, Station and even in UI-Kit.

**QA testing**
- N/A

**Comment by SlnPons** [comment]
@mazmassa what does cypress do? 
And as this seems to be sth we need to add in all repos where we use FE, is there a smart (smarter?) way to address all the "add cypress" tickets we have?
Keen to understand the details so I can prioritise correctly :)

**Comment by mazmassa** [comment]
> @mazmassa what does cypress do? And as this seems to be sth we need to add in all repos where we use FE, is there a smart (smarter?) way to address all the "add cypress" tickets we have? Keen to understand the details so I can prioritise correctly :)

Just updated! Let me know otherwise.

**Comment by pivilartisant** [comment]
Done
