### ISSUE TITLE
TS Interfaces/Types

### ISSUE THREAD

**Issue by mazmassa** [massalabs/station-massa-wallet#477]
We have a bunch of Interfaces/Types created on the fly.
We should first remove the export for the ones that are not exported. Secondly we must extract them into a specific file in the same dir of the file component.

TODO : 

- [x] #500
- [ ] extract interfaces to specific files
- [ ] Rework naming of different interfaces

**Comment by SlnPons** [comment]
@mazmassa assigning you so you can answer the question from Paul just above. But also, let's make sure to add more info & details in the ticket. 
It's complicated for them to understand what to do and for me to prioritise if I don't have the "why" explained ;) 
thank youuu 🙏

**Comment by longgamma-massa** [comment]
@mazmassa we need your inputs as Solene mentioned above for this issue.

**Comment by mazmassa** [comment]
Closing since we already changed the mentioned code and we have no standard for that as mentioned.
