### ISSUE TITLE
Fix Wails Pop Up Size 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#483]
**Context**
The size of the wails pop up does not correspond to the design 

https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=562-9571&mode=design&t=4xNgArS0VLFYlrgi-4

![Screenshot from 2023-06-29 09-28-23](https://github.com/massalabs/station/assets/90157528/161fd49f-2513-48e4-be1a-1c6795432dee)

**How to**
Change the wails - react front end code. It should be around 300px x 300px

![Screenshot from 2023-06-29 11-56-04](https://github.com/massalabs/station-massa-wallet/assets/90157528/f6395e32-1b65-40d7-8a65-f1864c842ed1)

**Comment by pivilartisant** [comment]
old issue : https://github.com/massalabs/station/issues/919

**Comment by pivilartisant** [comment]
@maxime-carabina  it seems it has been fixed, or that the bug was isolated on my screen, would you mind testing for me and show me the results ?

**Comment by maxime-carabina** [comment]
> 

Yes 😉 ! It's fixed here : https://github.com/massalabs/station-massa-wallet/pull/464

**Comment by pivilartisant** [comment]
> > 
> 
> Yes wink ! It's fixed here : #464

Nice i will close this issue :))

**Comment by SlnPons** [comment]
Thanks guys!! :)
