### ISSUE TITLE
Wails popup screen too small 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#493]
**Describe the bug**
Wails screen is too small 

**To Reproduce**

1. Open Massa Station
2. Launch the wallet via home page
3. Click on import an account to open wails screen 

**Expected behavior**
The wails screen should be 300px x 300px 

**Screenshots**
![Screenshot from 2023-07-03 12-30-20](https://github.com/massalabs/station-massa-wallet/assets/90157528/f96f44bb-359b-4179-a837-528173551421)

**MassaStation version**
0.2.4-dev

**Desktop (please complete the following information):**
-Linux ubuntu 22.04
Chrome

**Comment by maxime-carabina** [comment]
@pivilartisant This bug is already fixed.
Check on `station-mass-wallet` repository 😉 

And it will be up to date on `station` when the manifest is updated.

Resolved here : https://github.com/massalabs/station-massa-wallet/pull/464
