### ISSUE TITLE
Confirmation send page - tooltip is not dynamic anymore

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#508]
**Describe the bug**
The tooltip is supposed to display the fees selected or added by end users. It used to be the case on the last release but on this version of the main it is not the case. 
This is a regression that we need to solve. 

**To Reproduce**
1. Go on your wallet
2. Send a tx and go to advanced section to change the fees (either use a preset one or a custom one)
3. Go on the confirmation page
4. Check the tooltips: the text is only showing the amount selected by default.

**Expected behavior**
The tooltip is dynamic and change based on the fees selected on the previous screen. 

**Screenshots**
<img width="1047" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/109611779/e90f01ee-7e4c-4381-bb81-dbe77fe89aaf">

**Massa Wallet version**
Main branch

**Comment by pivilartisant** [comment]
Trying to think globally, should the user even be able to send MAS with 0 fees ? @SlnPons
