### ISSUE TITLE
Wallet import - not redirected to account selection

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#509]
**Context**
As a user, when I use the wallet for the 1st time (ie: no wallet created) and that I decide to import a new wallet, once i've finished the import, I am not redirected to my account selection list so I'm stuck. 

I should be redirected to the account list automatically and I should see the account I just imported.

see video

**User flow**
see above

**How to**

- [ ] once the import is successful, redirect to the account selection page immediately.

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

https://github.com/massalabs/station-massa-wallet/assets/109611779/f8cdaeeb-5c9b-41b8-886d-eaaae30ff275

**QA testing**
follow user flow

**Comment by Pierregvx** [comment]
I think I got what you're expecting when I tried on main @SlnPons  :thinking: 
[Screencast from 07-07-2023 08:52:58.webm](https://github.com/massalabs/station-massa-wallet/assets/83134981/bac50f0a-fa5e-44cf-9bdc-b65757455e2d)

**Comment by pivilartisant** [comment]
I also have this issue on MacOs
