### ISSUE TITLE
Update signature bytes and string encoding

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/station-massa-wallet#512]
**Context**
Starting from testnet 23, signatures are now versioned, both in string and bytes representations.
The wallet code needs to be updated accordingly.
Documentation detailing the changes can be found [here](https://github.com/massalabs/massa/issues/3988)

**How to**
- As the node is expecting a versioned signature, the wallet should return the versioned signature instead of the non-versioned one when signing an operation and returning the B58 encoded string.
- Write a function that will add a version to the bytes of the signature and return the versioned signature as a byte array.
- In the **Sign()** function, add the byte version to the signature bytes before returning it.

**QA testing**
QA testing should be done on the **whole wallet scope** in one swoop once all PR related to testnet 23 are merged in one branch to facilitate testing.

**Comment by gregLibert** [comment]
Furthermore, the signature shall be organize in a way that simplify usage by external applications such as teh transaction spammer
