### ISSUE TITLE
Display errors wails popup

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#528]
**Describe the bug**

When I click on Sign in the Wail "Sign a transaction" popup, I have no way to see the error.

**To Reproduce**

use mirage to mock the API call to return a 500 error

**Expected behavior**

Like in other wails pages, I want to see a red message explaining me that something went wrong.

**Screenshots**

<img width="516" alt="Screenshot 2023-07-13 at 14 21 12" src="https://github.com/massalabs/station-massa-wallet/assets/11590067/c7262817-c573-4433-a2ce-1cf7948b584a">

**MassaStation version**
The version of MassaStation the bug is present in.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: latest

**Additional context**

I experienced this while updating to testnet 23: the signature was created with a versioned public key and testnet 21 can't handle this.

**Comment by longgamma-massa** [comment]
@Thykof update me if it's still an issue with testnet 24.1

**Comment by Thykof** [comment]
Yes the issue is still present

**Comment by Thykof** [comment]
The user won't see the sign popup if the operation is not valid or is not base64 valid. In case of that error the wallet sign endpoint returns an error.

The caller of the sign endpoint (massa station, plugin, dapp, wallet provider) will have to handle the error returned by the wallet sign API endpoint (http call).

**Comment by Thykof** [comment]
We improved the way errors or shown in the different wails popups.

**Comment by longgamma-massa** [comment]
how to q/a?
