### ISSUE TITLE
Use massa-station log pkg

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#538]
Everywhere we use the built-in "log" package, we should instead use massa-station log pkg.

              What about using massa-station log pkg instead ?

_Originally posted by @gregLibert in https://github.com/massalabs/station-massa-wallet/pull/537#discussion_r1269097845_

**Comment by longgamma-massa** [comment]
[wallet-plugin_darwin-arm64 (2).zip](https://github.com/massalabs/station-massa-wallet/files/12682843/wallet-plugin_darwin-arm64.2.zip)

**Comment by Thykof** [comment]
QA: 
- ubuntu: OK
- macos: OK
- windows: we only avec the first line, and see this error during development: https://github.com/massalabs/station-massa-wallet/pull/753#issuecomment-1728380189

**Comment by Thykof** [comment]
QA update:
- windows: we tested again on 2 laptop, it works as expected
