### ISSUE TITLE
When updating station and wallet I lose my accounts

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/station-massa-wallet#542]
**Describe the bug**
I updated station to the latest version and after the wallet plugin and my wallets are not here anymore.

**To Reproduce**

1. Update station to the latest version
2. Relaunch station
3. Update wallet using the orange double arrow button
4. The wallet is unaccessible 
5. I restart station
6. I can access wallet but I have no wallets anymore

**Expected behavior**
See my wallets and keep my money

**Screenshots**
<img width="629" alt="Screenshot 2023-07-25 at 11 29 28" src="https://github.com/massalabs/station-massa-wallet/assets/32803821/fd188c29-bd7f-4586-af65-774c61a61fb3">

**MassaStation version**
0.3.0

**Desktop (please complete the following information):**
 - MacOS
 - chrome
 - Ventura 13.1.4

## QA
- install manually plugin https://github.com/massalabs/station-massa-wallet/releases/tag/v0.1.5
- create an account
- install manually plugin of main branch (with `task install-plugin`)
- see message:
![image](https://github.com/massalabs/station-massa-wallet/assets/11590067/48c4279f-50ef-4e46-b758-d2d2309cfa0f)

**Comment by longgamma-massa** [comment]
CC @mazmassa @peterjah

**Comment by pivilartisant** [comment]
I believe that I also encountered this issue while updating the wallet. I saw that there was no wallets, and when I tried importing an old account here is what happened : there is a wails screen that exists and "warns" us that something went wrong : 
<img width="611" alt="Screenshot 2023-07-26 at 14 09 09" src="https://github.com/massalabs/station-massa-wallet/assets/90157528/d509a006-601d-46b5-9ec3-10775ca1aeca">
Should we modify this error message ?

**Comment by longgamma-massa** [comment]
Nice catch @pivilartisant. You tried to pass the .yaml file?
If yes: I think this issue is already being solved, but will let @peterjah to confirm. 
If not: in case this error can still appear, we should add the better message description.

**Comment by pivilartisant** [comment]
> Nice catch @pivilartisant. You tried to pass the .yaml file? If yes: I think this issue is already being solved, but will let @peterjah to confirm. If not: in case this error can still appear, we should add the better message description.

Yeah exactly the .yaml file

**Comment by longgamma-massa** [comment]
P1: simple warning message displayed to the user (validated) https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=5007-30545&mode=design&t=exb9585Hcoqa3CTE-0


P3 (nice to have): Develop a flow for exporting, and then importing private keys for the accounts whose file format is incompatible - nice to have version. Can be a followup issue 
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=5001-30321&mode=design&t=Wq7yGSvMg84GoZVY-0

**Comment by longgamma-massa** [comment]
> Nice catch @pivilartisant. You tried to pass the .yaml file? If yes: I think this issue is already being solved, but will let @peterjah to confirm. If not: in case this error can still appear, we should add the better message description.

@peterjah can we get an answer here?

**Comment by peterjah** [comment]
nothing changed on this. The user have to select a file, so we must handle all cases where he gives us an old wallet, and also any rando file, to display a proper error message

**Comment by longgamma-massa** [comment]
@Thykof I couldn't test this scenario as part of Q/A. Need dev help in understanding how to test previous versions

**Comment by Thykof** [comment]
> @Thykof I couldn't test this scenario as part of Q/A. Need dev help in understanding how to test previous versions

I have update the issue description: added the QA steps. I tested, it works like expected.

**Comment by Thykof** [comment]
QA KO: I can see my previous invalid accounts in the list. When I click on the one with invalid format, there is an error. 

Expected behavior: I only see the account that have the correct format in that list (top right corner in the wallet plugin)

![Image](https://github.com/massalabs/station-massa-wallet/assets/11590067/eb424f00-2d96-42c8-b314-68baaa80643a)
