### ISSUE TITLE
Errors for importing unsupported .yaml format

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#579]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*
follow up issue of #542.

User is adding .yaml file but the format is not supported 

**User flow**
- User follows the 'Import existing account' flow.
- User selects option to upload .yaml file
- Display error when file format is unsupported

**How to**
- Error message:
" Unsupported file format. Please, try another file or import the account by providing private keys. "

**Technical details**
- tbd

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

<img width="607" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/113043914/c4ede5f4-f671-4b20-a423-7b1f5a52e66f">

**Comment by longgamma-massa** [comment]
@Thykof I added this as a followup to the current task of @Pierregvx (see comments in #542)

**Comment by Thykof** [comment]
I think a proper message would be more:

 "Unsupported file format. Please, try another file or import the account by providing private keys."

**Comment by longgamma-massa** [comment]
edited, great

**Comment by longgamma-massa** [comment]
needs Q/A that can mimic the breaking change error @Thykof

**Comment by Thykof** [comment]
> needs Q/A that can mimic the breaking change error @Thykof

I have tested, it works as expected

<img width="965" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/11590067/a66b066b-3003-40a6-a4ba-2296944897ba">
