### ISSUE TITLE
Sign operation: extract CallSC operation info and send it to wails popup

### ISSUE THREAD

**Issue by peterjah** [massalabs/station-massa-wallet#588]
**Context**
To be able to show informations about what operation you are signing

**How to**
When user submit a transaction through the sign endpoint, we should get all informations we need and attach it to the wails popup

**Comment by Thykof** [comment]
QA OK

<img width="545" alt="Screenshot 2023-08-21 at 17 12 47" src="https://github.com/massalabs/station-massa-wallet/assets/11590067/cc1553ce-7e7f-4c8e-82fe-aef456c83671">
