### ISSUE TITLE
 Keep wallet files upon uninstall of Station

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#594]
**Context**
Wallet files (.yaml) are currently stored in the same directory as other stations Files/folders. We experienced a few issues because of this approach on install and uninstall side. 

Wallet .yaml files allow users to import existing accounts, with the current limitation of not being backward compatible. 

For uninstall:
- Given than user doesn't back up the wallet account (via exporting .yaml file and/or saving private keys), once he uninstalls Station on all OS (**to be confirmed**), we delete wallet files. This will lead to permanent loss of funds.
Some related issues: massalabs/station#1073 

For install/update:
- Recognized wallet files following the supported format, should be recognized in the wallet UI.

**How to**

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
I propose to store the wallet files and assets.json in:
- `~/.massa-station-wallet` for Ubuntu and MacOS
- `%APPDATA%/massa-station-wallet` for Windows

**Comment by longgamma-massa** [comment]
working as expected when followed Q/A steps

**Comment by longgamma-massa** [comment]
Done on MacOS M1

**Comment by Thykof** [comment]
QA on windows: it works
