### ISSUE TITLE
Add Assets Page Confirmation Screen

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#601]
**Context**
To complete this: https://github.com/massalabs/station-massa-wallet/issues/457  

We must : 

- [ ] create de FE screens 
- [ ] add name & assetAddress  in the POST return on the BE side 

<img width="507" alt="Screenshot 2023-08-14 at 09 56 39" src="https://github.com/massalabs/station-massa-wallet/assets/90157528/4e937edb-a9fc-48ea-985c-08ccc21f795c">

**Comment by Thykof** [comment]
the issue description is out of date: we now want a toast instead of a popup for the success/failure page
