### ISSUE TITLE
Send ICO-quest results from Massa wallet

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#608]
**Context**
Massa Station (Wallet) will participate in ICO quests. 

The list of quests identified:
1. [Create a wallet account](https://www.notion.so/massa-innoteam/Station-Create-a-wallet-b909acebdd6e4c6393c2a42ef33ebb1b?pvs=4) (quest name: CREATE_WALLET)
2. [Pay an invoice with Massa wallet](https://www.notion.so/massa-innoteam/Station-Pay-an-invoice-d5a003f217014143995edc4a30b17d85?pvs=4) (quest name: PAY_INVOICE)

We must be able to record which addresses completed quests on the Buildnet, so that quest-users can recieve points for the quest completion.

**User flow**
1. User follows quest steps
2. We must register the address that finalized a quest. 

For CREATE_WALLET: we register the wallet address created.
For PAY_INVOICE: we register the address who got paid. That will be the wallet address that generated the link for payment, but at the moment when this wallet address actually got paid, via the shared (generated) link.

**How to**
- [ ] Suggested methods to fetch and send results are [given here](https://discord.com/channels/761151090673844244/1134022109824294942/1138491639355154572). 
- [ ] In case we go with the 'post method', there are security measures to be taken. Details [here](https://discord.com/channels/761151090673844244/1134022109824294942/1140652353888997446)
- Quest-names for post method should be sent in all CAPS.

**Technical details**
This new feature should not break the wallet in case of quest API is down, (because of outage or simply because api quest is over)

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
@Thykof after we q/a the Upload website feature

**Comment by thomas-senechal** [comment]
Hi @longgamma-massa 
Could you confirm me a few things ? 
1. What is the project name for those quests ? 
2. For the `CREATE_WALLET` quest, do we want to also validate the quest if a user imports an existing wallet ? Or only when it's created ?

**Comment by longgamma-massa** [comment]
1. names are exactly how I wrote in description :)
<img width="514" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/113043914/8f415d97-5980-4885-853e-dd248d9ebab1">

2. only when created, we don't count imported wallets from other wallet providers

**Comment by longgamma-massa** [comment]
@thomas-senechal I misread your q, my bad: project name 'massastation'

**Comment by longgamma-massa** [comment]
@thomas-senechal and @peterjah confirm with Leo B. that all quests are properly sent/stored please. After you check that endpoints send proper results, we can close the issue.

**Comment by thomas-senechal** [comment]
> @thomas-senechal and @peterjah confirm with Leo B. that all quests are properly sent/stored please. After you check that endpoints send proper results, we can close the issue.

I already discussed with Leo to know how to check if quests are validated correctly of if I made something wrong, and everything is working as expected ! 
I can show you if needed
