### ISSUE TITLE
I can see my previous invalid accounts in the list

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#623]
QA KO: I can see my previous invalid accounts in the list. When I click on the one with invalid format, there is an error. 

Expected behavior: I only see the account that have the correct format in that list (top right corner in the wallet plugin)

![Image](https://github.com/massalabs/station-massa-wallet/assets/11590067/eb424f00-2d96-42c8-b314-68baaa80643a)

_Originally posted by @Thykof in https://github.com/massalabs/station-massa-wallet/issues/542#issuecomment-1686337585_

**Comment by longgamma-massa** [comment]
@Thykof can you confirm that this appears only between the breaking change versions?

**Comment by Thykof** [comment]
> @Thykof can you confirm that this appears only between the breaking change versions?

No, it appears when you have an account file that is wrongly formatted. 

You end up with a wrongly formatted account file on these cases:
- breaking change versions (keep in mind that appart from now we will implement retrocompatibility
- user or another malicious software sabotage the account file.

**Comment by longgamma-massa** [comment]
'appart from now' you mean 'from now (this release)'?

We need to do this task for mainnet-ready.

**Comment by Thykof** [comment]
I mean that if you generated account file with wallet v0.1.5, you will have wrongly formatted yaml file. Because we didn't implement retrocompatibility with that version. Appart from now, we will implement retrocompatibility, which means from version v0.2.0, the only way to end up with wrongly formatted account is sabotage the file.

**Comment by longgamma-massa** [comment]
@gregLibert ping

**Comment by Thykof** [comment]
@gregLibert I have added the How to section in the issue description

**Comment by Thykof** [comment]
added QA steps and tested: it works
