### ISSUE TITLE
Cannot send coins to contract address

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/station-massa-wallet#633]
**Describe the bug**
Wallet does not allow to send coin to a contract address

**To Reproduce**
1. Go to massa station wallet
2. Click on send
3. Enter a contract address ex: AS12J5GFW1QTjGQyZ4HRYUZxFT6PjNDUE94rdW5PGnntib4pYZs9A
4. See error : Recipient address is not a valid Massa address

**Expected behavior**
We should be able to send coins to a smart contract

**Screenshots**
![Screenshot 2023-08-24 at 10 11 20](https://github.com/massalabs/station-massa-wallet/assets/44082144/d8ca1015-4e43-4693-96e8-62aea0d53def)

**MassaStation version**
Latest

**Comment by longgamma-massa** [comment]
@gregLibert @peterjah need your inputs on this need.

**Comment by gregLibert** [comment]
@Ben-Rey what is the use case ? i'm not sure we should allow this.

**Comment by Ben-Rey** [comment]
That's a misunderstanding on my side sorry, we can close it
