### ISSUE TITLE
Implement Sign a message  plain text and byte text

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#636]
**Context**
Implement sign a message with two variations

**User flow**

<img width="716" alt="Screenshot 2023-08-24 at 10 58 14" src="https://github.com/massalabs/station-massa-wallet/assets/90157528/a3969064-2904-46b6-b801-3607006a4dd1">

**Comment by longgamma-massa** [comment]
@mazmassa I think it relates to what you're doing?

**Comment by mazmassa** [comment]
> @mazmassa I think it relates to what you're doing?

https://github.com/massalabs/station-massa-wallet/pull/682
