### ISSUE TITLE
Implement Sign a message plain text

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station-massa-wallet#651]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**MassaStation version**
The version of MassaStation the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

**Additional context**

**Comment by longgamma-massa** [comment]
how to q/a this? just all 'sign a message' windows when they are merged? @B-Naoufal
