### ISSUE TITLE
Add the display of the account name and address on the popup of signing

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/station-massa-wallet#678]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

In the quest platform I ask people to sign a message with all of the addresses on massa wallet, it opens a popup one by one for each address but in the popup you don't have info of which address is signing

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

Add the display of the account name and address on the popup

**How to**
*List the step-by-step to get it do if needed - PM*

Add the display of the account name and address on the popup

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
- Following the discussion in gChat, let's include the wallet address as it exists in the backend. 
- For Account name - not a priority to do now. We can tackle it in the follow up issue if it some work.

@LucasF243 I think we need to add Wallet address: [hash] in the designs.

**Comment by longgamma-massa** [comment]
#691
