### ISSUE TITLE
refactor base URL: add constants

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#68]
Non blocking:  I think we should have some constants also here. Isn't it!?

```
export const BASE = {
    THYRA: "/thyra/plugin",
   ADDRESSES: "/massa/addresses"
}
```
then, 

```
`${BASE.THYRA}?attributes=balance&addresses=${address}`
...
`${BASE.ADDRESSES}?attributes=balance&addresses=${address}`
```

WDYT!?

_Originally posted by @mazmassa in https://github.com/massalabs/thyra-plugin-wallet/pull/67#discussion_r1155765480_

**Comment by SlnPons** [comment]
Hey @Thykof could you update this issue please? 
As I read thyra in it; I'm not sure it's up to date. It will help me to prioritise it :)
thx

**Comment by Thykof** [comment]
This issue is about legacy code that have been removed since, so closing
