### ISSUE TITLE
 "Massa Wallet" instead 'wallet-plugin' in the dock

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#690]
Change the name of the module in the dock to: Massa Wallet (all OSs)

![Image](https://github.com/massalabs/station-massa-wallet/assets/11590067/ec7721e3-1f5e-4863-abf3-f0e3e46d4971)

_Originally posted by @Thykof in https://github.com/massalabs/station-massa-wallet/issues/423#issuecomment-1713307502_

**Comment by SlnPons** [comment]
Same as: https://github.com/massalabs/station-massa-wallet/issues/689
