### ISSUE TITLE
Add 'from' account name to 'Sign' wails popup

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#691]
Context:
For Account name some work has been done by Pierre S on it in the backend, to allow showing account names in the signature popup. It will allow users to easily verify from which wallet they are signing a message or an operation.

Need:
Keep the address as well, but add the account name when applicable.

**Comment by pivilartisant** [comment]
@LucasF243 are there designs for this ? / should we do a quick sync to align (i feel like full designs are not necessary) :) 
cc @longgamma-massa

**Comment by longgamma-massa** [comment]
check comment here: https://github.com/massalabs/station-massa-wallet/issues/380#issuecomment-1803628956
