### ISSUE TITLE
Select any wallet-account to pay via payment link

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#692]
**Context**
Allow users to pay via link from any selected wallet account in the drop-down.

**User flow**
Incorrect (current):
1. have more than 1 wallet account
2. generate payment link with account 1: 'send/receive' page -> generate link pop up.
3. share the generated URL with yourself in another tab
4. try to select other wallet-account to pay the link
5. UI sends to homepage -> therefore, we are unable to pay with any other wallet-account.

**How to**
- on Step 4. user should be able to select a wallet account with which he wants to execute the payment.

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by mazmassa** [comment]
This was fixed here: https://github.com/massalabs/station-massa-wallet/pull/703
