### ISSUE TITLE
Change type for all amounts from number to bigint or string

### ISSUE THREAD

**Issue by peterjah** [massalabs/station-massa-wallet#720]
**General context about javascript number type**
Javascript number type limitation:
JS max safe inter: 9007199254740991
JS max safe floating point for 9 precision digits: 8,388,608 (see this: https://stackoverflow.com/a/57225494 )

This means:
If using number to represent nanoMas (inter value)
dealing with an amount > 9007199254740991 nanoMas (= 9007199,254740991 MAS) the operations on it are not safe.

If using number to represent MAS (floating point with 9 decimals)
dealing with an amount > 8388608 MAS the operations on it are not safe.

**How to handle this?**
we have 2 options: using strings wich is good for keep the value and display but we cant do any mathematical operations.
If we need do to some maths we have to use a big number library (BigInt is the js native one)

**Todo:**
remove all amount stored on numbers like here:
https://github.com/massalabs/station-massa-wallet/blob/a12f06206415358685bb239190ba32ffa434c627/wails-frontend/src/utils/massaFormat.tsx#L19-L29

**Comment by Thykof** [comment]
where to act:

- https://github.com/massalabs/station-massa-wallet/blob/0357187392f6aa60050e93751109fa723c63b50f/web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx#L20
- https://github.com/massalabs/station-massa-wallet/blob/0357187392f6aa60050e93751109fa723c63b50f/web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx#L41
