### ISSUE TITLE
bug of zeros in transfer coins

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/station-massa-wallet#727]
**Context**

<img width="1207" alt="Screenshot_2023-09-14_at_17 23 49" src="https://github.com/massalabs/station-massa-wallet/assets/16125633/746e9442-8944-4c70-9571-47cb87549461">

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by B-Naoufal** [comment]
@pivilartisant can you check on your side please , i guess the issue is coming from formatStandard function in https://github.com/massalabs/station-massa-wallet/blob/main/wails-frontend/src/utils/massaFormat.tsx , but this function is working well for sign callSC, and all operations except transfer it adds some Trailing zeros

**Comment by pivilartisant** [comment]
If the function works well in callSc and other instances my guess is that it comes from the amount being sent vie de sendCoins page, I will investigate and report back here

**Comment by pivilartisant** [comment]
The bug comes from the remove formatting operation when using the react currency  lib :
```
const formattedNum = formatValue({
    value: numInMas,
    groupSeparator: ',',
    decimalSeparator: '.',
    decimalScale: 9,
  });
```

When the be receives the Amount string from transfer it does not apply the correct formatting. @B-Naoufal  can you confirm that the callSc and other operations have an initial type of bigint ?

**Comment by B-Naoufal** [comment]
> The bug comes from the remove formatting operation when using the react currency lib :
> 
> ```
> const formattedNum = formatValue({
>     value: numInMas,
>     groupSeparator: ',',
>     decimalSeparator: '.',
>     decimalScale: 9,
>   });
> ```
> 
> When the be receives the Amount string from transfer it does not apply the correct formatting. @B-Naoufal can you confirm that the callSc and other operations have an initial type of bigint ?

@yes w are using bigInt for all operations now

**Comment by pivilartisant** [comment]
> > The bug comes from the remove formatting operation when using the react currency lib :
> > ```
> > const formattedNum = formatValue({
> >     value: numInMas,
> >     groupSeparator: ',',
> >     decimalSeparator: '.',
> >     decimalScale: 9,
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the be receives the Amount string from transfer it does not apply the correct formatting. @B-Naoufal can you confirm that the callSc and other operations have an initial type of bigint ?
> 
> @yES w are using bigInt for all operations now

So from what I understand we have three options: 
1) The most optimized and robust fix would be linked to what @peterjah is saying in this issue : https://github.com/massalabs/station-massa-wallet/issues/720 : FE sent a bigInt and not a string (significant refactor, I imagine it evry time consuming)
2)We could also continue using a str type as Amount and refactor the current formatStandard function (and possibly remove trailing zeros) to handle both cases correctly as it was originally intended (we might have to use another lib or write our own function to add comma separators?). 
3)We can add a removeTransferTrailingZeros function that handle the specific case for transfer (tested already and is working as expected) so we would not have to modify the current code to much and avoid unexpected problems (quick and easy solution imo)

cc @mazmassa  @peterjah  @Thykof

**Comment by pivilartisant** [comment]
> The bug comes from the remove formatting operation when using the react currency lib :
> 
> ```
> const formattedNum = formatValue({
>     value: numInMas,
>     groupSeparator: ',',
>     decimalSeparator: '.',
>     decimalScale: 9,
>   });
> ```
> 
> When the be receives the Amount string from transfer it does not apply the correct formatting. @B-Naoufal can you confirm that the callSc and other operations have an initial type of bigint ?

Edit, it doesn't seam to come from here, it seems that the removeTrailingZeros doesn't consider "10,000.000000000" (transfer amount) and a match to the ```const regex = /^(\d+)(\.\d*[1-9])?$/;``` regex

**Comment by pivilartisant** [comment]
https://github.com/massalabs/station-massa-wallet/pull/732 I think this should do the trick
