### ISSUE TITLE
Sign operation UI issue when sending MAS with 7+ decimals 

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#738]
**Context**
Sending MAS amounts with maximum decimals is currently like this: 
<img width="509" alt="image" src="https://github.com/massalabs/station-massa-wallet/assets/113043914/6d5edd7a-36ce-42f3-ac70-38da9954a2d0">

**How to**
- Make sure that the amounts are displayed in a proper way. Maybe we can decrease the font in such cases?
@LucasF243 @mazmassa 

**Technical details**
tbd by dev

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by pivilartisant** [comment]
@mazmassa  && @LucasF243  what do you think the best solution would be here ?

**Comment by LucasF243** [comment]
just reduce the font

**Comment by pivilartisant** [comment]
@mazmassa we should sync on how to do this best

**Comment by mazmassa** [comment]
> just reduce the font
Yeah... Indeed! Should be enough. Not too much but a bit yes! :)

**Comment by mazmassa** [comment]
This is fixed here: 

https://github.com/massalabs/station-massa-wallet/pull/757
https://github.com/massalabs/ui-kit/pull/335
