### ISSUE TITLE
Add Jest to web-frontend

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#742]
**Context**
Add jest to web front end to be able to conduct unit tests 

Objective is to standardize testing in order to have an optimized q/a  flow

**Comment by longgamma-massa** [comment]
@pivilartisant Please specify for which unit tests? What is the need?  I put should-have but to be confirmed.

**Comment by pivilartisant** [comment]
As of right now, there is no precise need, the objective is to install and set it up so when we want to modify a feature we may want to write a test to make sure that these modifications don't introduce a regression somewhere else

**Comment by pivilartisant** [comment]
We are closing this, after syncing with @mazmassa  it was determined that it was not necessary
