### ISSUE TITLE
Installing Wallet Archive Creates Extra Account

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station-massa-wallet#743]
**Describe the bug**
When installing an archive version of wallet (while having most up to date version with at least one account) the user can se an extra account in the account dropdown with no name associated. 

**To Reproduce**

1. Delete Current Wallet
2. Copy and paste link to download a Wallet archive 
3. Go through install flow & open wallet
4. See extra account

**Screenshots**
<img width="294" alt="Screenshot 2023-09-19 at 09 44 24" src="https://github.com/massalabs/station-massa-wallet/assets/90157528/a0e56a4f-5abb-4f72-941d-982a03b51104">

**MassaStation version**
v0.2.6 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox

**Additional context**
When clicking on the profile the user is redirected to user page

**Comment by pivilartisant** [comment]
It seems that there was a mismatch between my build an release accounts, I am not encountering this bug anymore

**Comment by Thykof** [comment]
It might be fixed here https://github.com/massalabs/station-massa-wallet/issues/623

**Comment by pivilartisant** [comment]
I haven't encountered it any more, so I will close
