### ISSUE TITLE
Wallet nickname rules should be same as from Node client

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#756]
**Context**
Issue coming from a user here: https://discord.com/channels/828270821042159636/1155836112540012626/1155836112540012626

**The need:**
- Make sure that the Wallet Nickname rules are the same as the ones from the node client.
- After that, we should update the standard to make sure that we use the same rules everywhere

**How to**
tbd

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
Will be closed with: https://github.com/massalabs/station-massa-wallet/issues/858 
@Thykof can you confirm please?

**Comment by Thykof** [comment]
> Will be closed with: #858 @Thykof can you confirm please?

yes
