### ISSUE TITLE
Sign operation - Add operation cost, hide technical parameters, edit fees 

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#786]
**Context**
Tackles the part of the Need 1 identified in the ['improvement of Sign operation' suggestions](https://github.com/massalabs/station-massa-wallet/issues/752) for SC-type operations, transaction and roll buy/sell initiated by a dapp. The need should also applied transactions sent in-app.

**User flow**
**All types of Operations initiated by dApps:**
- initiate operations types 
- Sign wails pop up is shown to the user.
- Display only the Operation cost, which is a sum of 'fees' + 'coins' parameters. 
- User must be able to edit parameter 'fees'.

**Sending Transactions in MW:**
- initiate MAS transfer in the wallet
- Sign wails pop up is shown to the user 
- instead of transaction fee show 'Operation cost' as mentioned above.
- User must be able to edit parameter 'fees'.

**How to**

- [x] #819
  - Enable editing 'fee' parameter. User should see the operation cost change due to his edit. 
  - User should be able to reset the 'fee' value to a recommended one by the initiator: dApp or Massa wallet.
- [x] #817 
- [ ] #814

Designs for Wails pop up: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=6671-41583&mode=design&t=eRL7yXNkjLB0lf71-0

Edit fees flow: https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=6845-13599&mode=design&t=YrmdmD91CV1EVFlo-0

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
QA ok
