### ISSUE TITLE
account file format: tolerance and follow more strictly the standard

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#858]
## Contact
Station Wallet had a requirement that was not present in the standard: it required wallet nicknames to be less than 32 characters long
- this was the cause of some compliant wallets to be rejected by Station Wallet
- this requirement is to be removed from Station Wallet to stop rejecting some standard-compliant wallets
- we also need to ensure that long nicknames are truncated in the UX

contrary to the standard, Station Wallet was cyphering not only the ed25519 secret key but the concatenation (secret_key, public_key)
- this can cause standard-compliant wallets to be rejected by Station Wallet
- it also causes Station-generated wallets to be non-compliant
- the encoding in Station Wallet is to be changed to comply with the standard when saving the wallet file
- tolerance is to be added both to Station Wallet and massa-client when loading wallet files to support both encoding formats to not break existing wallets incorrectly generated by Station

contrary to the standard, massa-client was setting the version number to "0" despite saving the wallet in otherwise standard-compliant "version 1" format,
- this was the cause of some massa-client wallets to be rightfully rejected by Station Wallet
- the massa-client was set to set the version to "1" when saving a wallet
- both massa-client and Station Wallet are to be set to interpret version "0" wallets as version "1" wallets provided that the encoded key is the right length to reject old (true version 0) wallets while ensuring that wallets generated with the broken v27 massa-client remain compatible with the latest versions of both wallets

On the core side: https://github.com/massalabs/massa/pull/4603

## How
Changes on the station wallet side:
  * When loading the wallet:
    * Accept wallet version 0 or 1 as version 1: [remove this line](https://github.com/massalabs/station-massa-wallet/blob/17d7f7cc9f4e722592dc0faf859e034bc276c039/pkg/wallet/account/account.go#L264)
    * require that the length of the public key is 33 (version byte plus 32 public key bytes)
  * When saving the wallet:
    * Include only the private key (version + 32 bytes) in the encrypted part (see standard) [here](https://github.com/massalabs/station-massa-wallet/blob/b832ae7493147e13911ad3c105acb3e6bf7c8b8f/pkg/types/object/object.go#L128)
  * when importing and creating an account
    * adjust UI to truncate (...) the nickname, like we do it already in the sign prompts
    * create a wallet: keep the limit at 32, import a private key: keep the limit at 32, import a yaml, limit at 53 (verify that 53 is the max length of an address)
  * tests
    * version 1 with public key in cipehered data (generate by massa wallet before this change)
    * version 1 (generated by massa-wallet after this change)
    * version 1 without public key in cipehered data (generated with massa-client after this change)
    * version 0 (generated by any software)
    * version 0 that is 1: keypair version is present (generated with massa-client before this change)

## QA
Massa-client to station wallet:
- generate a wallet in branch labnet of massa-client
- import it in massa-station-wallet branch account-nickname-change-constraint
- try to submit an operation (signature must be accepted by the node)

Station Wallet to massa-client:
- generate a wallet in branch account-nickname-change-constraint of massa-station-wallet with password of you massa-client
- export the yaml file
- rename it manually, in the nickname in the file and in the filename: put the address for the nickname
- copy it in massa/massa-client/wallets
- try to submit an operation in massa-client: buyroll <address> 1 1 (signature must be accepted by the node)

**Comment by damip** [comment]
> Require that the length of the decoded plaintext be 33 or 65 bytes. We need the password for that, we have the password only when the user sign a message or an operation [here](https://github.com/massalabs/station-massa-wallet/blob/aa8793ae74bf68a2725de0a4c96de81a2c0cbf1f/pkg/types/encrypted_private_key.go#L189).

@Thykof what do you currently do if you discover that the deciphered plaintext does not properly deserialize into a private key ? I guess you display some kind of error message to the user ? If so, we should do the same there

**Comment by Thykof** [comment]
> > Require that the length of the decoded plaintext be 33 or 65 bytes. We need the password for that, we have the password only when the user sign a message or an operation [here](https://github.com/massalabs/station-massa-wallet/blob/aa8793ae74bf68a2725de0a4c96de81a2c0cbf1f/pkg/types/encrypted_private_key.go#L189).
> 
> @Thykof what do you currently do if you discover that the deciphered plaintext does not properly deserialize into a private key ? I guess you display some kind of error message to the user ? If so, I think we should do the same if the length is incorrect.

we don't do that, we sign and if an error occur we display an error but in the sign prompt, not in the import process
