### ISSUE TITLE
Enable multi token types management within one account

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station-massa-wallet#93]
**Context**
Part of mainnet plan - [Wallet product milestone 2](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4)

--> the objective of this issue is to enable users to manage multiple token types (FT & NFT) in one account.

**User flow**
As design here: TO BE ADDED

**How to**

- [ ] Add the possibility to manage fungible tokens in one account
- [ ] Add the possibility to manage NFT in one account
- [ ] Enable all token types to be transferred between accounts
- [ ] Create appropriate front-end to surface the correct info as designed

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

We will need to store the list of smart contracts that the user follows.

filename: `tokens_{nickname}.json`
location: same as account yaml file
content: json

```json
[
  {
    "type": "NFT",
    "address": "AS..."
  }
]
```

**QA testing**
Follow the user flow

**Comment by Thykof** [comment]
I propose to split into multiple issues:
- manager tokens: add, remove token smart contracts
- transfer FT
- transfer NFT

**Comment by SlnPons** [comment]
Sounds good to me! Validate this with @peterjah so we can tackle them in the right order.

We should probably start with a small issue to "extract all info that we'll receive from the blockchain about token SC" so that while you work on the back-end with @LucasF243 we can finalise the exact wording for the front-end. WDYT?

**Comment by Thykof** [comment]
> extract all info that we'll receive from the blockchain about token SC

These info will come from the block feeder database.

We can start with adding back-end tasks: API endpoints

**Comment by SlnPons** [comment]
> Will be postpone ! Need Block API, and it is not planned for now.

**Comment by SlnPons** [comment]
Closing as duplicate of https://github.com/massalabs/station-massa-wallet/issues/457
