### ISSUE TITLE
upload zip artifact in github action

### ISSUE THREAD

**Issue by Thykof** [massalabs/station-massa-wallet#96]
Original commit sha: d4ab27e

              There is a probleme here. upload artifact action takes some files and put it into a zip.
So here you are creating a zip into a zip

_Originally posted by @peterjah in https://github.com/massalabs/thyra-plugin-wallet/pull/89#discussion_r1166418725_

**Comment by SlnPons** [comment]
I think this is done now. @Thykof can you confirm and close please? :)

**Comment by Thykof** [comment]
true!
